CREATE TABLE "measurements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"measurement_date" date NOT NULL,
	"weight" numeric(5, 2) NOT NULL,
	"triceps" numeric(5, 2),
	"subscapular" numeric(5, 2),
	"chest" numeric(5, 2),
	"midaxillary" numeric(5, 2),
	"suprailiac" numeric(5, 2),
	"abdominal" numeric(5, 2),
	"thigh" numeric(5, 2),
	"neck" numeric(5, 2),
	"shoulders" numeric(5, 2),
	"chest_circ" numeric(5, 2),
	"waist" numeric(5, 2),
	"hip" numeric(5, 2),
	"left_thigh" numeric(5, 2),
	"right_thigh" numeric(5, 2),
	"left_calf" numeric(5, 2),
	"right_calf" numeric(5, 2),
	"left_bicep_relaxed" numeric(5, 2),
	"right_bicep_relaxed" numeric(5, 2),
	"left_bicep_flexed" numeric(5, 2),
	"right_bicep_flexed" numeric(5, 2),
	"body_fat_percentage" numeric(5, 2),
	"navy_body_fat_percentage" numeric(5, 2),
	"lean_mass" numeric(5, 2),
	"fat_mass" numeric(5, 2),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "measurements" ADD CONSTRAINT "measurements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;